version: '2.2'
services:

  # The Application
  app:
    build:
      context: ./
      dockerfile: app.dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www:delegated
      - /var/www/node_modules
    env_file:
      - .docker.env
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=database"
      - "REDIS_HOST=redis"
      - "REDIS_PORT=6379"
    ports:
      - 9000:9000

  # The Web Server
  web:
    build:
      context: ./
      dockerfile: web.dockerfile
    working_dir: /var/www
    volumes_from:
      - app
    ports:
      - 8080:80

  queue:
    build:
      context: ./
      dockerfile: app.dockerfile
    working_dir: /var/www
    depends_on:
      - database
      - redis
    env_file:
      - .docker.env
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=database"
      - "REDIS_HOST=redis"
      - "REDIS_PORT=6379"

    volumes:
      - ./:/var/www:delegated
      - /var/www/node_modules
    command:
      - /usr/bin/supervisord
      - -n
      - -c
      - /etc/supervisord.conf

  # The Database
  database:
    image: mysql:5.7
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=secret"
      - "MYSQL_DATABASE=homestead"
      - "MYSQL_USER=homestead"
    ports:
        - "33062:3306"

  redis:
    image: redis:4.0
    ports:
      - "63791:6379"

volumes:
  dbdata:
